version: "3.8"

x-healthcheck-db-template: &pghealthcheck
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U postgres"]
    interval: 30s
    timeout: 30s
    retries: 3

services:
  app:
    build: ./
    depends_on:
      - postgresdb
    env_file:
      - ./.env
    environment:
      - DB_HOST=postgresdb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - ./:$WORKDIR
      - ./logs:$WORKDIR/logs
      - ./dist/:$WORKDIR/dist/
  postgresdb:
    image: postgres:14-alpine
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
    ports:
      - $DB_PORT:5432
    volumes:
      - ./db:/var/lib/postgresql/data